#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# If the SSH key path is not provided, set it to an empty string
if [ -z "$ssh_key" ]; then
    ssh_key=""
else
    ssh_key="-i $ssh_key"
fi

if scp -o StrictHostKeyChecking=no "$ssh_key" "$file_path" "$username@$server_ip":~/; then
    echo "File transfer successful!"
else
    echo "File transfer failed."
fi
