#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine

# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a basic HTML file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Ensure Nginx is listening on port 80
sudo sed -i 's/^\(listen\s*.*\)80/\180/' /etc/nginx/sites-available/default

# Reload Nginx configuration
sudo /etc/init.d/nginx reload

# Output success message
echo "Nginx installed and configured. Testing with curl:"
curl localhost
