#!/usr/bin/env bash
#a Bash script that configures an Ubuntu server

sudo cp /etc/hosts.backup /etc/hosts

echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
